name: atmosfx_video_player
description: Play Videos for atmosfx video portraits. It needs to load 3 video players at the same time and play the correct video for each group.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
